### ISSUE TITLE
无法获取海报

### ISSUE THREAD

**Issue by helloweiya** [azureqaq/tjuptattendance#8]
![image](https://user-images.githubusercontent.com/92931441/225202027-5652eeb7-5c0e-448c-a43c-87c11ad3df5a.png)

**Comment by azureqaq** [comment]
请问：
1. 是使用的最新版本吗？
2. 这种错误消息出现的频率如何？
3. 是否是短时间内多次尝试？

**Comment by helloweiya** [comment]
1. 由于GitHub上传的release存在依赖问题，拉取最新的source并自行编译 ，rust版本为1.67.1 (d5a82bbd2 2023-02-07)
2. 还未尝试tjuptatt，感谢分享
3. 尝试访问[doubanapi](https://movie.douban.com/j/subject_suggest?q=%E4%B8%89%E4%BD%93)有返回信息，结果如下
```
[{
	"episode": "30",
	"img": "https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2886492021.jpg",
	"title": "三体",
	"url": "https:\/\/movie.douban.com\/subject\/26647087\/?suggest=%E4%B8%89%E4%BD%93",
	"type": "movie",
	"year": "2023",
	"sub_title": "三体",
	"id": "26647087"
}, {
	"episode": "15",
	"img": "https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2885057891.jpg",
	"title": "三体",
	"url": "https:\/\/movie.douban.com\/subject\/34444648\/?suggest=%E4%B8%89%E4%BD%93",
	"type": "movie",
	"year": "2022",
	"sub_title": "三体",
	"id": "34444648"
}, {
	"episode": "8",
	"img": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2885006319.jpg",
	"title": "三体 第一季",
	"url": "https:\/\/movie.douban.com\/subject\/35196946\/?suggest=%E4%B8%89%E4%BD%93",
	"type": "movie",
	"year": "2023",
	"sub_title": "Three-Body Problem",
	"id": "35196946"
}, {
	"episode": "unknow",
	"img": "https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2887525403.jpg",
	"title": "三体II：黑暗森林",
	"url": "https:\/\/movie.douban.com\/subject\/36231281\/?suggest=%E4%B8%89%E4%BD%93",
	"type": "movie",
	"year": "2026",
	"sub_title": "三体II：黑暗森林",
	"id": "36231281"
}, {
	"episode": "",
	"img": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2264149578.jpg",
	"title": "三体",
	"url": "https:\/\/movie.douban.com\/subject\/21335171\/?suggest=%E4%B8%89%E4%BD%93",
	"type": "movie",
	"year": "2030",
	"sub_title": "三体",
	"id": "21335171"
}]
```
4. 今天又出现了不同的情况，显示为无法获取海报，无法获取豆瓣数据。3.12-3.14正常使用，3.15开始出现这个问题
![image](https://user-images.githubusercontent.com/92931441/225488699-81139b84-f9ff-4254-97d7-c2cba1dae732.png)

**Comment by azureqaq** [comment]
感谢你的反馈

因为本项目依赖豆瓣API，而豆瓣API仅允许短时间内调用 `5` 次，如果超过这个限制则会返回空数据：`[]`。这种情况下就会导致错误信息：`无法获取豆瓣数据`

可以通过在 [doubanapi](https://movie.douban.com/j/subject_suggest?q=%E4%B8%89%E4%BD%93) 页面短时间内多次刷新来验证

相关代码在: [这里](https://github.com/azureqaq/tjuptattendance/blob/master/src/libs/picparser.rs#L147)

```rust
async fn get_douban_data(name: &str, client: &Client) -> Result<DouBanData> {
    let res: Vec<DouBanData> = client
        .get("https://movie.douban.com/j/subject_suggest")
        .query(&[("q", name)])
        .send()
        .await?
        .json()
        .await?;

    // log::debug!("豆瓣数据: {}个", res.len());

    if let Some(d) = res.into_iter().next() {
        Ok(d)
    } else {
        Err(anyhow!("无法获取豆瓣数据"))
    }
}
```

这种问题 **只能过段时间再试**

由于豆瓣API的限制，导致签到重试时 **几乎不能成功**，所以 *暂时* 推荐的方式是使用 [crontab](https://www.runoob.com/linux/linux-comm-crontab.html) 来多设置多个触发时间，多试几次。比如 `0 * * * * /path/to/tjuptattendance --flag` (每小时尝试一次)

我已经开始着手重构并尝试解决豆瓣API的问题(处于非常早期的阶段，详见 [rebuild](https://github.com/azureqaq/tjuptattendance/tree/rebuild) 分支)，但由于我的时间、精力、水平有限，可能需要很久一段时间才有可能完成。

如果你有任何建议欢迎再次 Issue 或 PR

**Comment by helloweiya** [comment]
非常感谢你的耐心解答和开发分享！
由于个人水平和近期精力有限，自己个人使用时临时采用硬编码使用IOS端通知[Bark](https://github.com/Finb/Bark)实现签到消息推送。
![41E01B1C8A049ABD18137A173F842A68](https://user-images.githubusercontent.com/92931441/225512193-596e0101-5a3c-4f91-a6b6-56a144e6185c.png)
希望能够重新考虑推送方面的可扩展性，方便引入更多的推送方式。
